$("#first").click(function(){
    console.log("show");
    $("#Resume").fadeIn(2000);
    $("#Service").fadeOut(2000);
    $("#pey").fadeOut(2000);
    $("#one").fadeOut(2000);
    $("#fitz").fadeOut(2000);
    $("#obj").fadeOut(2000);
    $("#gro").fadeOut(2000);
    $("#players").fadeOut(2000);
    $("#goat").fadeOut(2000);
});
$("#two").click(function(){
    console.log("show");
    $("#Job").fadeIn(2000);
    $("#Education").fadeOut(2000);
});
$("#third").click(function(){
    console.log("show");
    $("#Resume").fadeOut(2000);
    $("#Service").fadeIn(2000);
});
$("#four").click(function(){
    console.log("show");
    $("#Job").fadeOut(2000);
    $("#Education").fadeIn(2000);
});